/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Modelos.Proveedor;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author edwin-993
 */
public class InterfazProveedor extends javax.swing.JFrame {

    /**
     * Creates new form InterfazProveedor
     */
    public InterfazProveedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbdFunciones = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblIdentificador = new javax.swing.JLabel();
        lblEmpresa = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCoordenadas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCiudad = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        btnAccion = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lblIdentificador1 = new javax.swing.JLabel();
        lblEmpresa1 = new javax.swing.JLabel();
        txtEmpresa1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        txtNombre1 = new javax.swing.JTextField();
        txtCorreo1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtTelefono1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtDireccion1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtCoordenadas1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtCiudad1 = new javax.swing.JTextField();
        txtEstado1 = new javax.swing.JTextField();
        btnAccion1 = new javax.swing.JButton();
        btnLimpiar1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        lblIdentificador2 = new javax.swing.JLabel();
        lblEmpresa2 = new javax.swing.JLabel();
        txtEmpresa2 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        txtNombre2 = new javax.swing.JTextField();
        txtCorreo2 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtTelefono2 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtDireccion2 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtCoordenadas2 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtCiudad2 = new javax.swing.JTextField();
        txtEstado2 = new javax.swing.JTextField();
        btnAccion2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegistros = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        cmbFiltro = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtCriterio = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbdFunciones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbdFunciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbdFuncionesMouseClicked(evt);
            }
        });

        jLabel1.setText("Identificador");

        lblIdentificador.setText("jLabel2");

        lblEmpresa.setText("Nombre de la empresa:");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de contacto", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel3.setText("Direccion");

        jLabel2.setText("Persona de contacto:");

        jLabel5.setText("Correo");

        jLabel4.setText("Numero de telefono");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDireccion)
                        .addGap(77, 77, 77))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtTelefono))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCorreo)
                        .addGap(94, 94, 94)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel6.setText("Coordenadas de ubicacion");

        jLabel7.setText("Ciudad:");

        jLabel8.setText("Estado:");

        btnAccion.setText("Guardar registro");

        btnLimpiar.setText("Limpiar campos");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblEmpresa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmpresa))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEstado))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCiudad))
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCoordenadas))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblIdentificador)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpiar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblIdentificador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmpresa)
                    .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCoordenadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLimpiar)
                    .addComponent(btnAccion, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAccion, btnLimpiar});

        tbdFunciones.addTab("Insertar", jPanel1);

        jLabel11.setText("Identificador");

        lblIdentificador1.setText("jLabel2");

        lblEmpresa1.setText("Nombre de la empresa:");

        txtEmpresa1.setEnabled(false);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de contacto", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        txtNombre1.setEnabled(false);

        txtCorreo1.setEnabled(false);

        jLabel12.setText("Direccion");

        txtTelefono1.setEnabled(false);

        jLabel13.setText("Persona de contacto:");

        txtDireccion1.setEnabled(false);

        jLabel14.setText("Correo");

        jLabel15.setText("Numero de telefono");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDireccion1)
                        .addGap(77, 77, 77))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(txtTelefono1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCorreo1)
                        .addGap(94, 94, 94)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtDireccion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtCorreo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel16.setText("Coordenadas de ubicacion");

        txtCoordenadas1.setEnabled(false);

        jLabel17.setText("Ciudad:");

        jLabel18.setText("Estado:");

        txtCiudad1.setEnabled(false);

        txtEstado1.setEnabled(false);

        btnAccion1.setText("Editar registro");
        btnAccion1.setEnabled(false);

        btnLimpiar1.setText("Limpiar y cancelar");
        btnLimpiar1.setEnabled(false);
        btnLimpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblEmpresa1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmpresa1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEstado1))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCiudad1))
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCoordenadas1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblIdentificador1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnAccion1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpiar1)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblIdentificador1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmpresa1)
                    .addComponent(txtEmpresa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtCoordenadas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtCiudad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtEstado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLimpiar1)
                    .addComponent(btnAccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAccion1, btnLimpiar1});

        tbdFunciones.addTab("Editar", jPanel3);

        jLabel19.setText("Identificador");

        lblIdentificador2.setText("jLabel2");

        lblEmpresa2.setText("Nombre de la empresa:");

        txtEmpresa2.setEnabled(false);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de contacto", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        txtNombre2.setEnabled(false);

        txtCorreo2.setEnabled(false);

        jLabel20.setText("Direccion");

        txtTelefono2.setEnabled(false);

        jLabel21.setText("Persona de contacto:");

        txtDireccion2.setEnabled(false);

        jLabel22.setText("Correo");

        jLabel23.setText("Numero de telefono");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre2))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDireccion2)
                        .addGap(77, 77, 77))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(txtTelefono2))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCorreo2)
                        .addGap(94, 94, 94)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(txtNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtDireccion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtCorreo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel24.setText("Coordenadas de ubicacion");

        txtCoordenadas2.setEnabled(false);

        jLabel25.setText("Ciudad:");

        jLabel26.setText("Estado:");

        txtCiudad2.setEnabled(false);

        txtEstado2.setEnabled(false);

        btnAccion2.setText("Eliminar");
        btnAccion2.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAccion2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblEmpresa2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmpresa2))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEstado2))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCiudad2))
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCoordenadas2, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblIdentificador2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(lblIdentificador2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmpresa2)
                    .addComponent(txtEmpresa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtCoordenadas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtCiudad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtEstado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAccion2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbdFunciones.addTab("Eliminar", jPanel5);

        tblRegistros.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificador", "Nombre", "Contacto", "Direccion", "Telefono", "Correo", "Coordenadas", "Ciudad", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRegistros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRegistrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRegistros);

        jLabel9.setText("Filtrar por:");

        cmbFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Identificador", "Nombre", "Contacto", "Direccion", "Telefono", "Correo", "Coordenadas", "Ciudad", "Estado" }));

        jLabel10.setText("Criterio de búsqueda:");

        btnRegresar.setText("Regresar al menu principal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tbdFunciones)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cmbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(tbdFunciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblRegistrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRegistrosMouseClicked
        // TODO add your handling code here:
        int filaSeleccionada = tblRegistros.getSelectedRow();
        tbdFunciones.setSelectedIndex(1);
        Insertar(false);
        Editar(true);
        Eliminar(false);
        
        this.setIdentificadorEditar(tblRegistros.getValueAt(filaSeleccionada,0).toString());
        this.setEmpresaEditar(tblRegistros.getValueAt(filaSeleccionada, 1).toString());
        this.setNombreEditar(tblRegistros.getValueAt(filaSeleccionada,2).toString());
        this.setDireccionEditar(tblRegistros.getValueAt(filaSeleccionada, 3).toString());
        this.setCorreoEditar(tblRegistros.getValueAt(filaSeleccionada, 5).toString());
        this.setTelefonoEditar(tblRegistros.getValueAt(filaSeleccionada, 4).toString());
        this.setCoordenadasEditar(tblRegistros.getValueAt(filaSeleccionada, 6).toString());
        this.setCiudadEditar(tblRegistros.getValueAt(filaSeleccionada, 7).toString());
        this.setEstadoEditar(tblRegistros.getValueAt(filaSeleccionada, 8).toString());
        
        this.setIdentificadorEliminar(tblRegistros.getValueAt(filaSeleccionada,0).toString());
        this.setEmpresaEliminar(tblRegistros.getValueAt(filaSeleccionada, 1).toString());
        this.setNombreEliminar(tblRegistros.getValueAt(filaSeleccionada,2).toString());
        this.setDireccionEliminar(tblRegistros.getValueAt(filaSeleccionada, 3).toString());
        this.setCorreoEliminar(tblRegistros.getValueAt(filaSeleccionada, 5).toString());
        this.setTelefonoEliminar(tblRegistros.getValueAt(filaSeleccionada, 4).toString());
        this.setCoordenadasEliminar(tblRegistros.getValueAt(filaSeleccionada, 6).toString());
        this.setCiudadEliminar(tblRegistros.getValueAt(filaSeleccionada, 7).toString());
        this.setEstadoEliminar(tblRegistros.getValueAt(filaSeleccionada, 8).toString());
    }//GEN-LAST:event_tblRegistrosMouseClicked

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        this.limpiarCampos();
        this.seleccionarAccion(0);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnLimpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiar1ActionPerformed
        // TODO add your handling code here:
        this.limpiarCampos();
        this.seleccionarAccion(0);
        
    }//GEN-LAST:event_btnLimpiar1ActionPerformed

    private void tbdFuncionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbdFuncionesMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        
        int filaSeleccionada = tblRegistros.getSelectedRow();
        switch (tbdFunciones.getSelectedIndex()) {
            case 0:
                Insertar(true);
                Editar(false);
                Eliminar(false);
                this.limpiarCampos();
                tblRegistros.clearSelection();
                break;
            case 1:
                if (filaSeleccionada < 0) {
                    mensajeError("Registro no seleccionado", "Seleccione un registro de la tabla para acceder a esta funcion...");
                    tbdFunciones.setSelectedIndex(0);
                    break;
                }
                Insertar(false);
                Editar(true);
                Eliminar(false);
                break;
            case 2:
                if (filaSeleccionada < 0) {
                    mensajeError("Registro no seleccionado", "Seleccione un registro de la tabla para acceder a esta funcion...");
                    tbdFunciones.setSelectedIndex(0);
                    break;
                }
                Insertar(false);
                Editar(false);
                Eliminar(true);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_tbdFuncionesMouseClicked

// Getters y setters de la interfaz:
    public void setIdentificadorInsertar(String identificador) {
        this.lblIdentificador.setText(identificador);
    }

    public String getEmpresaInsertar() {
        return txtEmpresa.getText();
    }
    
    public String getNombreInsertar(){
        return txtNombre.getText();
    }
    
    public String getDireccionInsertar() {
        return txtDireccion.getText();
    }

    public String getTelefonoInsertar() {
        return txtTelefono.getText();
    }

    public String getCorreoInsertar() {
        return txtCorreo.getText();
    }

    public String getCoordenadasInsertar() {
        return txtCoordenadas.getText();
    }

    public String getCiudadInsertar() {
        return txtCiudad.getText();
    }

    public String getEstadoInsertar() {
        return txtEstado.getText();
    }

    public void setEmpresaInsertar(String valor) {
        txtEmpresa.setText(valor);
    }

    public void setNombreInsertar(String valor){
        this.txtNombre.setText(valor);
    }
    
    public void setDireccionInsertar(String valor) {
        txtDireccion.setText(valor);
    }

    public void setTelefonoInsertar(String valor) {
        txtTelefono.setText(valor);
    }

    public void setCorreoInsertar(String valor) {
        txtCorreo.setText(valor);
    }

    public void setCoordenadasInsertar(String valor) {
        txtCoordenadas.setText(valor);
    }

    public void setCiudadInsertar(String valor) {
        txtCiudad.setText(valor);
    }

    public void setEstadoInsertar(String valor) {
        txtEstado.setText(valor);
    }

    public String getIdentificadorEditar() {
        return lblIdentificador1.getText();
    }

    public String getEmpresaEditar() {
        return txtEmpresa1.getText();
    }

    public String getNombreEditar(){
        return txtNombre1.getText();
    }
    
    public String getDireccionEditar() {
        return txtDireccion1.getText();
    }

    public String getTelefonoEditar() {
        return txtTelefono1.getText();
    }

    public String getCorreoEditar() {
        return txtCorreo1.getText();
    }

    public String getCoordenadasEditar() {
        return txtCoordenadas1.getText();
    }

    public String getCiudadEditar() {
        return txtCiudad1.getText();
    }

    public String getEstadoEditar() {
        return txtEstado1.getText();
    }
    
    private void setIdentificadorEliminar(String toString) {
        this.lblIdentificador2.setText(toString);
    }
    
    private void setIdentificadorEditar(String identificador){
        this.lblIdentificador1.setText(identificador);
    }

    public void setEmpresaEditar(String valor) {
        txtEmpresa1.setText(valor);
    }

    public void setDireccionEditar(String valor) {
        txtDireccion1.setText(valor);
    }

    public void setNombreEditar(String valor){
        this.txtNombre1.setText(valor);
    }
    
    public void setTelefonoEditar(String valor) {
        txtTelefono1.setText(valor);
    }

    public void setCorreoEditar(String valor) {
        txtCorreo1.setText(valor);
    }

    public void setCoordenadasEditar(String valor) {
        txtCoordenadas1.setText(valor);
    }

    public void setCiudadEditar(String valor) {
        txtCiudad1.setText(valor);
    }

    public void setEstadoEditar(String valor) {
        txtEstado1.setText(valor);
    }

    public String getIdentificadorEliminar() {
        return lblIdentificador2.getText();
    }

    public void setEmpresaEliminar(String valor) {
        txtEmpresa2.setText(valor);
    }

    public void setDireccionEliminar(String valor) {
        txtDireccion2.setText(valor);
    }

    public void setNombreEliminar(String valor){
        this.txtNombre2.setText(valor);
    }
    
    public void setTelefonoEliminar(String valor) {
        txtTelefono2.setText(valor);
    }

    public void setCorreoEliminar(String valor) {
        txtCorreo2.setText(valor);
    }

    public void setCoordenadasEliminar(String valor) {
        txtCoordenadas2.setText(valor);
    }

    public void setCiudadEliminar(String valor) {
        txtCiudad2.setText(valor);
    }

    public void setEstadoEliminar(String valor) {
        txtEstado2.setText(valor);
    }

//  Mensajes de la interfaz
    public void mensajeError(String titulo, String contenido) {
        JOptionPane.showMessageDialog(this, contenido, titulo, JOptionPane.ERROR_MESSAGE);
    }

    public int mensajeConfirmacion(String titulo, String contenido) {
        return JOptionPane.showConfirmDialog(this, contenido, titulo, JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
    }

    public void mensajeInformacion(String titulo, String contenido) {
        JOptionPane.showMessageDialog(this, contenido, titulo, JOptionPane.PLAIN_MESSAGE);
        
    }

    public void mensajeConsola(String texto) {
        System.out.println(texto);
    }

//  Activacion de secciones
    public void Insertar(boolean activacion) {
        txtEmpresa.setEnabled(activacion);
        txtNombre.setEnabled(activacion);
        txtDireccion.setEnabled(activacion);
        txtTelefono.setEnabled(activacion);
        txtCorreo.setEnabled(activacion);
        txtCoordenadas.setEnabled(activacion);
        txtCiudad.setEnabled(activacion);
        txtEstado.setEnabled(activacion);
        btnAccion.setEnabled(activacion);
        btnLimpiar.setEnabled(activacion);
        btnRegresar.setEnabled(activacion);
    }

    public void Editar(boolean activacion) {
        txtEmpresa1.setEnabled(activacion);
        txtNombre1.setEnabled(activacion);
        txtDireccion1.setEnabled(activacion);
        txtTelefono1.setEnabled(activacion);
        txtCorreo1.setEnabled(activacion);
        txtCoordenadas1.setEnabled(activacion);
        txtCiudad1.setEnabled(activacion);
        txtEstado1.setEnabled(activacion);
        btnAccion1.setEnabled(activacion);
        btnLimpiar1.setEnabled(activacion);
        btnRegresar.setEnabled(!activacion);
    }

    public void Eliminar(boolean activacion) {
        btnAccion2.setEnabled(activacion);
        btnRegresar.setEnabled(!activacion);
    }

//  Limpieza de campos
    public void limpiarCampos(){
        txtNombre.setText("");
        txtNombre1.setText("");
        txtNombre2.setText("");
        txtEmpresa.setText("");
        txtEmpresa1.setText("");
        txtEmpresa2.setText("");
        txtDireccion.setText("");
        txtDireccion1.setText("");
        txtDireccion2.setText("");
        txtTelefono.setText("");
        txtTelefono1.setText("");
        txtTelefono2.setText("");
        txtCorreo.setText("");
        txtCorreo1.setText("");
        txtCorreo2.setText("");
        txtCoordenadas.setText("");
        txtCoordenadas1.setText("");
        txtCoordenadas2.setText("");
        txtCiudad.setText("");
        txtCiudad1.setText("");
        txtCiudad2.setText("");
        txtEstado.setText("");
        
        lblIdentificador1.setText("");
        lblIdentificador2.setText("");
        tblRegistros.clearSelection();
    }
    
//  Validacion de datos
    public boolean validarInsertar(){
        boolean isValidEmpresa = !this.getEmpresaInsertar().isEmpty();
        boolean isValidNombre = !this.getNombreInsertar().isEmpty();
        boolean isValidDireccion = !this.getDireccionInsertar().isEmpty();
        boolean isValidTelefono = !this.getTelefonoInsertar().isEmpty();
        boolean isValidCorreo = !this.getCorreoInsertar().isEmpty();
        boolean isValidCoordenadas = !this.getCoordenadasInsertar().isEmpty();
        boolean isValidCiudad = !this.getCiudadInsertar().isEmpty();
        boolean isValidEstado = !this.getEstadoInsertar().isEmpty();
        
        return isValidEmpresa && isValidNombre && isValidDireccion 
                && isValidTelefono && isValidCorreo && isValidCoordenadas
                && isValidCiudad && isValidEstado;
    }
    
    public boolean validarEditar(){
        boolean isValidEmpresa = !this.getEmpresaEditar().isEmpty();
        boolean isValidNombre = !this.getNombreEditar().isEmpty();
        boolean isValidDireccion = !this.getDireccionEditar().isEmpty();
        boolean isValidTelefono = !this.getTelefonoEditar().isEmpty();
        boolean isValidCorreo = !this.getCorreoEditar().isEmpty();
        boolean isValidCoordenadas = !this.getCoordenadasEditar().isEmpty();
        boolean isValidCiudad = !this.getCiudadEditar().isEmpty();
        boolean isValidEstado = !this.getEstadoEditar().isEmpty();
        
        return isValidEmpresa && isValidNombre && isValidDireccion 
                && isValidTelefono && isValidCorreo && isValidCoordenadas
                && isValidCiudad && isValidEstado;
    }
    
    public boolean confirmEliminar() {
        return mensajeConfirmacion("Confirmar eliminacion de registro", "¿Está usted seguro de querer eliminar el registro seleccionado?\n"
                + "Esta accion no se puede deshacer una vez realizada") == JOptionPane.YES_OPTION;
    }
    
//  EventListeners para notificar al controlador de las operaciones CRUD
    public void addInsertarEventListener(ActionListener listener){
        btnAccion.addActionListener(listener);
    }
    
    public void addEditarEventListener(ActionListener listener){
        btnAccion1.addActionListener(listener);
    }
    
    public void addEliminarEventListener(ActionListener listener){
        btnAccion2.addActionListener(listener);
    }
    
//  Funciones de utilidad para la interfaz
    public void seleccionarAccion(int indice){
        this.tbdFunciones.setSelectedIndex(indice);
        switch(indice){
            case 1:
                Insertar(true);
                Editar(false);
                Eliminar(false);
                break;
            case 2:
                Insertar(false);
                Editar(false);
                Eliminar(false);
                break;
            case 3:
                Insertar(false);
                Editar(false);
                Eliminar(false);
                break;
        }
    }
    
    public void actualizarTabla(List<Proveedor> listaProveedores){
        DefaultTableModel modeloTabla = (DefaultTableModel) tblRegistros.getModel();
        modeloTabla.setRowCount(0);
        mensajeConsola("Actualizando tabla");
        for (Proveedor proveedor : listaProveedores) {
            int identificador = proveedor.getIdProveedor();
            String empresa = proveedor.getEmpresa();
            String nombre = proveedor.getNombreContacto();
            String direccion = proveedor.getDireccion();
            String telefono = proveedor.getTel();
            String correo = proveedor.getCorreo();
            String coordenadas = proveedor.getCoordenadas();
            String ciudad = proveedor.getCiudad();
            String estado = proveedor.getEstado();
            Object[] fila = {identificador,empresa,nombre,direccion,telefono,correo,coordenadas,ciudad,estado};
            modeloTabla.addRow(fila);
        }
        tblRegistros.setModel(modeloTabla);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccion;
    private javax.swing.JButton btnAccion1;
    private javax.swing.JButton btnAccion2;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnLimpiar1;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cmbFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEmpresa;
    private javax.swing.JLabel lblEmpresa1;
    private javax.swing.JLabel lblEmpresa2;
    private javax.swing.JLabel lblIdentificador;
    private javax.swing.JLabel lblIdentificador1;
    private javax.swing.JLabel lblIdentificador2;
    private javax.swing.JTabbedPane tbdFunciones;
    private javax.swing.JTable tblRegistros;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtCiudad1;
    private javax.swing.JTextField txtCiudad2;
    private javax.swing.JTextField txtCoordenadas;
    private javax.swing.JTextField txtCoordenadas1;
    private javax.swing.JTextField txtCoordenadas2;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtCorreo1;
    private javax.swing.JTextField txtCorreo2;
    private javax.swing.JTextField txtCriterio;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDireccion1;
    private javax.swing.JTextField txtDireccion2;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtEmpresa1;
    private javax.swing.JTextField txtEmpresa2;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtEstado1;
    private javax.swing.JTextField txtEstado2;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtNombre2;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelefono1;
    private javax.swing.JTextField txtTelefono2;
    // End of variables declaration//GEN-END:variables

    
}
